<?php 
    require 'lib/Plog.php'; 
?>

<!doctype html>
<?php Plog::route() ?>
<html>
  <head>
    <meta charset="utf-8">
    <title><?php echo Plog::title().' - '.$CONFIG['general']['title'] ?></title>
    <link rel="stylesheet"
          href="<?php echo Plog::root() ?>/node_modules/bootstrap/dist/bootstrap.min.css">
    <link rel="stylesheet"
          href="<?php echo Plog::root() ?>/node_modules/bootswatch/dist/<?php echo $CONFIG['page']['theme'] ?>/bootstrap.min.css">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="<?php echo Plog::root() ?>">
                <?php echo $CONFIG['general']['title']?>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>
    </header>

    <main class="container">
      <?php echo Plog::content() ?>
    </main>
    
    <footer class="container">
      Copyright &copy;
      <?php echo date('Y') ?>
      <?php echo $CONFIG['general']['author'] ?>
      &lt;<a href="<?php echo $CONFIG['general']['email'] ?>"><?php echo $CONFIG['general']['email'] ?></a>&gt;
      All Rights Reserved.<br />
      Generated by <a href="https://github.com/asciian/plog">Plog</a>.
    </footer>

    <script src="<?php echo Plog::root() ?>/node_modules/popper.js/dist/popper.min.js"></script>
    <script src="<?php echo Plog::root() ?>/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="<?php echo Plog::root() ?>/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
  </body>
</html>
