<?php 
    require 'lib/Plog.php'; 
?>

<!doctype html>
<?php Plog::route() ?>
<html>
  <head>
    <meta charset="utf-8">
    <title><?php echo Plog::title().' - '.$CONFIG['general']['title'] ?></title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://bootswatch.com/<?php echo $CONFIG['page']['theme'] ?>/bootstrap.min.css">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default navbar-static-top">
      	<div class="container-fluid">
      	  <div class="navbar-header">
      	    <a class="navbar-brand" href="<?php echo Plog::root() ?>">
      	      <?php echo $CONFIG['general']['title']?>
      	    </a>
      	  </div>
      	</div>
      </nav>
    </header>
    <main class="container">
      <?php echo Plog::content() ?>
    </main>
    <footer class="container">
      Copyright &copy;
      <?php echo date('Y') ?>
      <?php echo $CONFIG['general']['author'] ?>
      &lt;<a href="<?php echo $CONFIG['general']['email'] ?>"><?php echo $CONFIG['general']['email'] ?></a>&gt;
      All Rights Reserved.<br />
      Generated by <a href="https://github.com/asciian/plog">Plog</a>.
    </footer>
  </body>
</html>
